# Generated by Django 5.0.6 on 2024-11-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slms_website', '0002_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='UserPreferences',
        ),
    ]
