# Generated by Django 5.0.6 on 2024-11-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slms_website', '0004_alter_user_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinghistory',
            name='book',
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='book_ids',
            field=models.JSONField(default=list),
        ),
    ]
